### ISSUE TITLE
Test Latest Updates to MailChimp API

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-mailchimp#3]
We need to test the latest updates to the master branch of this add-on. 

For backstory, see Codebase ticket: 
https://events.codebasehq.com/projects/event-espresso/tickets/9462

And Grinder post: 
http://p2.eventespresso.com/2018/08/22/need-to-finish-updating-the-mailchimp-api-to-v3/

Testing notes to follow.

**Comment by sethshoultes** [comment]
**What changed:**
2.4.0 DMS were removed, so no EE migrations should be invoked when coming from MC v2.3. Those DB migrations/updates (if they are needed) are now done for each event individually. They are executed when the admin visits the event edit page and when a registrant subscribes to an event, before he is submitted to MC.

**Testing notes:**
The requests to the API can be seen on the bottom of the page here: https://us8.admin.mailchimp.com/account/api/
* In an older version of MC, like v2.3.4.p create a few events (4 or 6) subscribed to different lists and/or different selection of interests (groups). Switch to this branch.
* For the first few (1, 2) events, try opening them in the admin edit page. The list and its interests should be displayed properly (as they were saved when using the older version of MC).
* Try to subscribe attendees for those same first few events. They should be submitted to MC lists with no issues.
* Now, for the other (2, 3) events, try to subscribe attendees for those without visiting their edit pages. They should still be submitted to MC lists.
* Try creating a few new events and adding attendees to those.

**Comment by sethshoultes** [comment]
@Pebblo and @joshfeck can you help with testing as well?

**Comment by sethshoultes** [comment]
I ran through the testing notes and didn't see any issues. I created several groups and events and ran through registration multiple times for each event. Each registration was assigned to the correct lists and groups.

**Comment by sethshoultes** [comment]
@Pebblo and @joshfeck what do you think about releasing this update?

**Comment by joshfeck** [comment]
Seems fine by me, but it'd be good to get Tony's thought on this matter.

**Comment by Pebblo** [comment]
@knazart or @mnelson4 

I think I remember this coming up from the first batch of testing but I now can't find any comments on it.

In this version of the add-on, the 'Email' field is missing from the selections within the event - https://monosnap.com/file/oJQcSKotiyG8iaoLAMr0ZQmwJizLvf

This is a screenshot from 2.3.5 - http://take.ms/I8ra5

Looking in the screenshots in the previous tickets, this looks expected as none of them show that field, however, if we previously allowed users to select a different email field is it a good idea to remove that functionality now?

**Comment by knazart** [comment]
I don't really remember removing that field. I also don't see where it could be excluded and the `Merge_Fields_Form` is still checking for that field. I'm inclined to think that it's a change on the MailChimp side. Maybe they don't allow it to be in the Merge Fields list and made it mandatory to default to the `email_address` which in our code is sent with each submission to MC anyways (as a mandatory subscription arg).

**Comment by Pebblo** [comment]
Hmm, yeah, but problem is that even if that's the case, this is going to break functionality for any user that uses an 'alternative' email field for subscriptions, and/or prevent any users from using an alternative email field from the registration form in the future.

Looking at the requests made with 2.3.5 and dumping our the subscribe args using the `FHEE__EE_MCI_Controller__mci_submit_to_mailchimp__subscribe_args` filter you get something like this:

`Array
(
    [apikey] => xxxxxx
    [id] => 506e9fd173
    [email] => Array
        (
            [email] => testuser@example.com
        )

    [double_optin] => 
    [merge_vars] => Array
        (
            [EMAIL] => altuser@example.com
            [FNAME] => ExampleAlt
            [LNAME] => ExampleAltLName
        )

)`

Doing so with master gives this:

`Array
(
    [email_address] => testuser@example.com
    [merge_vars] => Array
        (
            [FNAME] => ExampleAlt
            [LNAME] => ExampleAltLName
        )

)`

So apparently the MC API version 1.3 allowed you to override the subscribe call by passing the email value with the merge vars, which isn't really a good idea (and likely why it was removed). Now with v3 EMAIL isn't a merge var, so it isn't listed as a choice on the event.... but what if you've been using this previously?

This change isn't going to affect the majority of users as they will likely be using the default field for email but its still possible for the above scenario.

Note I also tried adding the 'EMAIL' field back to the merge vars using the filter and I get this response from mailchimp:

> Cannot have different values for 'email_address', 'merge_fields.EMAIL', and 'merge_fields.MERGE0'. Only one of these fields is required, or their valu

(Yes the mailchimp log cuts off the remainder of the message)

So this may not be a bad thing considering GDPR etc and people need to be really transparent about who is being added to the list meaning defaulting to always being the actual attendee is probably a good thing. But this is an important change that may affect more users than we know.

To be clear, I'm not against releasing this as is but I think at least @joshfeck should be aware of this change incase it comes up.

**Comment by sethshoultes** [comment]
@Pebblo thanks for the review. Can users roll back to the previous version if they are affected by this? If so, we could roll out a release, and if it breaks for someone, they could roll back while we look into the issue further. Thoughts?

**Comment by Pebblo** [comment]
If they can roll back I think they'd need to go into any event that has migrated to v3, reselect the email field and save the settings, right @knazart ?

**Comment by knazart** [comment]
> Now with v3 EMAIL isn't a merge var, so it isn't listed as a choice on the event.... but what if you've been using this previously?

For truth, I wold expect myself to test that particular scenario happening, but because the work here was done a bit of some time ago I'm not sure how well that was tested.

>If they can roll back I think they'd need to go into any event that has migrated to v3, reselect the email field and save the settings

That sounds right Tony, but again, we should also test that roll back scenario before we release this. If there is an issue there then create and prioritize a ticket for it.

**Comment by sethshoultes** [comment]
@Pebblo can you run any additional testing you can think of?

**Comment by Pebblo** [comment]
Looks like the above is irrelevant now as it appears MailChimp have patched this in v2 of the API.

I tested using 2.3.5.p to confirm the original behaviour and now the 'EMAIL' merge var is ignored on that version anyway, so the subscribe call always uses the EE 'email' field.

The subscribe args are still the same:

```
Array
(
    [apikey] => xxxxxx
    [id] => 506e9fd173
    [email] => Array
        (
            [email] => testuser@example.com
        )

    [double_optin] => 
    [merge_vars] => Array
        (
            [EMAIL] => altuser@example.com
            [FNAME] => ExampleAlt
            [LNAME] => ExampleAltLName
        )

)
```

But `[EMAIL]` is not used.

----

There is, however, a problem with this in the latest version. If you update from 2.3.5 to the latest master and an event has an alt email set, it breaks the subscriptions with this error:

> Cannot have different values for 'email_address', 'merge_fields.EMAIL', and 'merge_fields.MERGE0'. Only one of these fields is required, or their values must be the same.

I think the migrations this add-on runs should take of this and update the merge vars, preventing the above from happening, right Nazar?

I switched back to 2.3.5, added a new event and set it up with that version and added a registration, all good.

Then de-activated the add-on switched to master and re-activated. On re-registering onto that 'new' event it should run a migration and update the vars, right? That doesn't seem to be happening.

How does the add-on determine if a migration should happen for a specific event?

**Comment by knazart** [comment]
Ok, yes, this is an issue. The migrations are still running in the scenario you described, it's just not managing the email merge field correctly because it was possible to change it in the 2.3.5.p. It should be possible to patch this up in the migration process.

I'll create an issue for this.

**Comment by Pebblo** [comment]
Ok, so the above is fixed and I've not found any other problems with the current version of master.

@joshfeck, as we've already had to pull back a release of this add-on, do you want another set of eyes on this? I'm confident its good to go tbh but just checking.

**Comment by Pebblo** [comment]
Latest version of MailChimp has now been pushed live. 

Closing this out.
